# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 13:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0002_auto_20170724_0212'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
