# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0003_auto_20170724_1313'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
