# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170724_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='secrets.User'),
        ),
    ]
