# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_cost',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_weight',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
